# Экспортируем все обработчики
from .common import *
from .registration import *
from .zakroi import *
from .fourx import *
from .raspash import *
from .beika import *
from .strochka import *
from .gorlo import *
from .ytyg import *
from .otk import *
from .upakovka import *
from .user_management import *
from .party_management import *